### ISSUE TITLE
Memory leak with optifine G7 in my pack

### ISSUE THREAD

**Issue by Mr-Syntax** [freeeranger/dark-caverns#5] opened 2021-09-16 18:46 UTC
so i made this pack, and initially when i checked out the caves it was fine, but then open further inspection i had a huge lag spike and maxxed out my ram :( i will gladely include the mod again but ill sadly have to remove it for now

**Comment by Mr-Syntax** [comment] 2021-09-16 18:47
https://www.curseforge.com/minecraft/modpacks/chosencraft

**Comment by freeeranger** [comment] 2021-09-16 20:15
Thanks for reporting! If you have the time, a log file would be really appreciated. Also, is this something that happens frequently or have you only experienced it once?

**Comment by Mr-Syntax** [comment] 2021-09-16 22:54
i didnt generate one but if you download the pack and just fly for 5-10 mins in one direction it happens, i think it might be a specific biome

**Comment by freeeranger** [comment] 2021-09-17 05:26
Aight,, I'm gonna download your pack and see if I can reproduce the issue, but chances are it was 1: a one time thing, 2: not a thing with my mod but with having 200+ mods installed. I'll see what I can find though

**Comment by freeeranger** [comment] 2022-01-11 00:34
closing for now since the mod doesn't seem to be the cause of this from my testing

**Closed as completed by freeeranger** 2022-01-11 00:34 UTC
